### ISSUE TITLE
fails with 3x3

### ISSUE THREAD

**Issue by kentor** [graemeboy/matrix-rotate#1]
in:

```
[ 
  [0,0,1],
  [0,0,0],
  [0,0,0],
]
```

out:

```
[ 
  [0,0,0],
  [0,0,0],
  [1,0,0],
]
```

expected:

```
[ 
  [0,0,0],
  [0,0,0],
  [0,0,1],
]
```

**Comment by graemeboy** [comment]
Thanks; this has been fixed.

**Comment by dmitry-dulevich** [comment]
@graemeboy no bro, it wasn't fixed. or you haven't updated npm
